"""
imuBias submodule
"""
from __future__ import annotations
import numpy
import numpy.typing
import typing
__all__: list[str] = ['ConstantBias']
class ConstantBias:
    @staticmethod
    def Identity() -> ConstantBias:
        ...
    def __add__(self, arg0: ConstantBias) -> ConstantBias:
        ...
    def __getstate__(self) -> tuple[str]:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, biasAcc: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"], biasGyro: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]) -> None:
        ...
    def __neg__(self) -> ConstantBias:
        ...
    def __repr__(self, s: str = '') -> str:
        ...
    def __setstate__(self, arg0: tuple) -> None:
        ...
    def __sub__(self, arg0: ConstantBias) -> ConstantBias:
        ...
    def accelerometer(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
        ...
    def correctAccelerometer(self, measurement: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"], H1: numpy.ndarray | None = None, H2: numpy.ndarray | None = None) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
        ...
    def correctGyroscope(self, measurement: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"], H1: numpy.ndarray | None = None, H2: numpy.ndarray | None = None) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
        ...
    def deserialize(self, serialized: str) -> None:
        ...
    def equals(self, expected: ConstantBias, tol: typing.SupportsFloat | typing.SupportsIndex) -> bool:
        ...
    def gyroscope(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
        ...
    def localCoordinates(self, b: ConstantBias) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[6, 1]"]:
        ...
    def print(self, s: str = '') -> None:
        ...
    def retract(self, v: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[6, 1]"]) -> ConstantBias:
        ...
    def serialize(self) -> str:
        ...
    def vector(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[6, 1]"]:
        ...
