"""
so3 submodule
"""
from __future__ import annotations
import numpy
import numpy.typing
import typing
__all__: list[str] = ['DexpFunctor', 'ExpmapFunctor', 'InvJKernel', 'Kernel']
class Kernel:
    def applyFrechet(self, v: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 3]"]:
        ...
    def applyLeft(self, v: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"], Hw: numpy.ndarray | None = None, Hv: numpy.ndarray | None = None) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
        ...
    def applyRight(self, v: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"], Hw: numpy.ndarray | None = None, Hv: numpy.ndarray | None = None) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
        ...
    def frechet(self, X: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 3]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 3]"]:
        ...
    def left(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 3]"]:
        ...
    def right(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 3]"]:
        ...
class InvJKernel:
    J: Kernel
    def applyLeft(self, v: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"], Hw: numpy.ndarray | None = None, Hv: numpy.ndarray | None = None) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
        ...
    def applyRight(self, v: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"], Hw: numpy.ndarray | None = None, Hv: numpy.ndarray | None = None) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
        ...
    def left(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 3]"]:
        ...
    def right(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 3]"]:
        ...
class ExpmapFunctor:
    nearZero: bool
    @typing.overload
    def __init__(self, omega: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]) -> None:
        ...
    @typing.overload
    def __init__(self, nearZeroThresholdSq: typing.SupportsFloat | typing.SupportsIndex, axis: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]) -> None:
        ...
    @typing.overload
    def __init__(self, axis: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"], angle: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    def expmap(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 3]"]:
        ...
    @property
    def A(self) -> float:
        ...
    @A.setter
    def A(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def B(self) -> float:
        ...
    @B.setter
    def B(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def W(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 3]"]:
        ...
    @W.setter
    def W(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 3]"]) -> None:
        ...
    @property
    def WW(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 3]"]:
        ...
    @WW.setter
    def WW(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 3]"]) -> None:
        ...
    @property
    def theta(self) -> float:
        ...
    @theta.setter
    def theta(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def theta2(self) -> float:
        ...
    @theta2.setter
    def theta2(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
class DexpFunctor(ExpmapFunctor):
    def C(self) -> float:
        ...
    def D(self) -> float:
        ...
    def E(self) -> float:
        ...
    def Gamma(self) -> Kernel:
        ...
    def InvJacobian(self) -> InvJKernel:
        ...
    def Jacobian(self) -> Kernel:
        ...
    def Rodrigues(self) -> Kernel:
        ...
    @typing.overload
    def __init__(self, omega: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]) -> None:
        ...
    @typing.overload
    def __init__(self, omega: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"], nearZeroThresholdSq: typing.SupportsFloat | typing.SupportsIndex, nearPiThresholdSq: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    def leftJacobian(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 3]"]:
        ...
    def rightJacobian(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 3]"]:
        ...
    @property
    def omega(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
        ...
