"""Generate type stubs for GTSAM, so editors can show its signatures.

GTSAM's Python package is a compiled extension with a ``py.typed`` marker and no
``.pyi`` files, so VS Code / Pylance (and any other static tool) sees nothing
inside it: no completion, no argument names, no tooltips. These stubs fix that.
They are written to ``typings/``, which is where Pylance and Pyright look by
default, and ``make_handout.py`` copies them into the handout.

The stubs describe the installed GTSAM version. Regenerate them whenever the
GTSAM pin in ``environment.yml`` changes. ``pybind11-stubgen`` does not need to
be in the environment; a throwaway install next to it is enough::

    python -m pip install --target .stubgen pybind11-stubgen
    PYTHONPATH=.stubgen python tools/make_gtsam_stubs.py      # Windows: set PYTHONPATH=.stubgen
"""

from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "typings"

# Plain-Python modules in the gtsam package that only re-export a compiled
# submodule. pybind11-stubgen stubs the submodule, not the wrapper, so the
# wrapper needs a one-line stub of its own or ``from gtsam.X import ...`` is
# unresolved.
REEXPORTS = ["symbol_shorthand", "noiseModel", "imuBias"]


def main() -> None:
    try:
        import gtsam  # noqa: F401
    except ImportError:
        sys.exit("gtsam is not importable: run this inside the ttk4250_ga2 environment.")

    if subprocess.run([sys.executable, "-c", "import pybind11_stubgen"]).returncode != 0:
        sys.exit("pybind11_stubgen is not importable; see the docstring of this script.")

    if OUT.exists():
        shutil.rmtree(OUT)

    subprocess.run(
        [sys.executable, "-m", "pybind11_stubgen", "gtsam", "-o", str(OUT), "--ignore-all-errors"],
        check=True,
    )

    for name in REEXPORTS:
        (OUT / "gtsam" / f"{name}.pyi").write_text(
            f"from gtsam.gtsam.{name} import *\n", encoding="utf-8"
        )

    version = subprocess.run(
        [sys.executable, "-m", "pip", "show", "gtsam"], capture_output=True, text=True
    ).stdout
    version = next((line for line in version.splitlines() if line.startswith("Version:")), "")
    (OUT / "README.md").write_text(
        "# GTSAM type stubs\n\n"
        "Generated by `tools/make_gtsam_stubs.py` from the installed GTSAM "
        f"({version.strip() or 'version unknown'}). They only give your editor GTSAM's "
        "signatures; nothing imports them at run time. Do not edit by hand.\n",
        encoding="utf-8",
    )

    count = sum(1 for _ in OUT.rglob("*.pyi"))
    print(f"wrote {count} stub files to {OUT}")


if __name__ == "__main__":
    main()
