"""
mEstimator submodule
"""
from __future__ import annotations
import collections.abc
import typing
__all__: list[str] = ['AsymmetricCauchy', 'AsymmetricTukey', 'Base', 'Cauchy', 'Custom', 'DCS', 'Fair', 'GemanMcClure', 'Huber', 'L2WithDeadZone', 'Null', 'TruncatedLeastSquares', 'Tukey', 'Welsch']
class Base:
    class ReweightScheme:
        """
        Members:
        
          Scalar
        
          Block
        """
        Block: typing.ClassVar[Base.ReweightScheme]
        Scalar: typing.ClassVar[Base.ReweightScheme]
        __members__: typing.ClassVar[dict[str, Base.ReweightScheme]]
        @typing.overload
        def __and__(self, other: Base.ReweightScheme) -> int:
            ...
        @typing.overload
        def __and__(self, other: typing.SupportsInt | typing.SupportsIndex) -> int:
            ...
        @typing.overload
        def __eq__(self, other: Base.ReweightScheme) -> bool:
            ...
        @typing.overload
        def __eq__(self, other: typing.SupportsInt | typing.SupportsIndex) -> bool:
            ...
        @typing.overload
        def __eq__(self, other: typing.Any) -> bool:
            ...
        @typing.overload
        def __ge__(self, other: Base.ReweightScheme) -> bool:
            ...
        @typing.overload
        def __ge__(self, other: typing.SupportsInt | typing.SupportsIndex) -> bool:
            ...
        def __getstate__(self) -> int:
            ...
        @typing.overload
        def __gt__(self, other: Base.ReweightScheme) -> bool:
            ...
        @typing.overload
        def __gt__(self, other: typing.SupportsInt | typing.SupportsIndex) -> bool:
            ...
        def __hash__(self) -> int:
            ...
        def __index__(self) -> int:
            ...
        def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None:
            ...
        def __int__(self) -> int:
            ...
        def __invert__(self) -> typing.Any:
            ...
        @typing.overload
        def __le__(self, other: Base.ReweightScheme) -> bool:
            ...
        @typing.overload
        def __le__(self, other: typing.SupportsInt | typing.SupportsIndex) -> bool:
            ...
        @typing.overload
        def __lt__(self, other: Base.ReweightScheme) -> bool:
            ...
        @typing.overload
        def __lt__(self, other: typing.SupportsInt | typing.SupportsIndex) -> bool:
            ...
        @typing.overload
        def __ne__(self, other: Base.ReweightScheme) -> bool:
            ...
        @typing.overload
        def __ne__(self, other: typing.SupportsInt | typing.SupportsIndex) -> bool:
            ...
        @typing.overload
        def __ne__(self, other: typing.Any) -> bool:
            ...
        @typing.overload
        def __or__(self, other: Base.ReweightScheme) -> int:
            ...
        @typing.overload
        def __or__(self, other: typing.SupportsInt | typing.SupportsIndex) -> int:
            ...
        @typing.overload
        def __rand__(self, other: Base.ReweightScheme) -> int:
            ...
        @typing.overload
        def __rand__(self, other: typing.SupportsInt | typing.SupportsIndex) -> int:
            ...
        def __repr__(self) -> str:
            ...
        @typing.overload
        def __ror__(self, other: Base.ReweightScheme) -> int:
            ...
        @typing.overload
        def __ror__(self, other: typing.SupportsInt | typing.SupportsIndex) -> int:
            ...
        @typing.overload
        def __rxor__(self, other: Base.ReweightScheme) -> int:
            ...
        @typing.overload
        def __rxor__(self, other: typing.SupportsInt | typing.SupportsIndex) -> int:
            ...
        def __setstate__(self, state: typing.SupportsInt | typing.SupportsIndex) -> None:
            ...
        def __str__(self) -> str:
            ...
        @typing.overload
        def __xor__(self, other: Base.ReweightScheme) -> int:
            ...
        @typing.overload
        def __xor__(self, other: typing.SupportsInt | typing.SupportsIndex) -> int:
            ...
        @property
        def name(self) -> str:
            ...
        @property
        def value(self) -> int:
            ...
    def __repr__(self, s: str = '') -> str:
        ...
    def print(self, s: str = '') -> None:
        ...
class Null(Base):
    @staticmethod
    def Create() -> Null:
        ...
    def __getstate__(self) -> tuple[str]:
        ...
    def __init__(self) -> None:
        ...
    def __setstate__(self, arg0: tuple) -> None:
        ...
    def deserialize(self, serialized: str) -> None:
        ...
    def graduatedLoss(self, error: typing.SupportsFloat | typing.SupportsIndex, mu: typing.SupportsFloat | typing.SupportsIndex) -> float:
        ...
    def graduatedWeight(self, error: typing.SupportsFloat | typing.SupportsIndex, mu: typing.SupportsFloat | typing.SupportsIndex) -> float:
        ...
    def loss(self, error: typing.SupportsFloat | typing.SupportsIndex) -> float:
        ...
    def serialize(self) -> str:
        ...
    def weight(self, error: typing.SupportsFloat | typing.SupportsIndex) -> float:
        ...
class Fair(Base):
    @staticmethod
    def Create(c: typing.SupportsFloat | typing.SupportsIndex, reweight: Base.ReweightScheme = ...) -> Fair:
        ...
    def __getstate__(self) -> tuple[str]:
        ...
    def __init__(self, c: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    def __setstate__(self, arg0: tuple) -> None:
        ...
    def deserialize(self, serialized: str) -> None:
        ...
    def graduatedLoss(self, error: typing.SupportsFloat | typing.SupportsIndex, mu: typing.SupportsFloat | typing.SupportsIndex) -> float:
        ...
    def graduatedWeight(self, error: typing.SupportsFloat | typing.SupportsIndex, mu: typing.SupportsFloat | typing.SupportsIndex) -> float:
        ...
    def loss(self, error: typing.SupportsFloat | typing.SupportsIndex) -> float:
        ...
    def serialize(self) -> str:
        ...
    def weight(self, error: typing.SupportsFloat | typing.SupportsIndex) -> float:
        ...
class Huber(Base):
    @staticmethod
    def Create(k: typing.SupportsFloat | typing.SupportsIndex, reweight: Base.ReweightScheme = ...) -> Huber:
        ...
    def __getstate__(self) -> tuple[str]:
        ...
    def __init__(self, k: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    def __setstate__(self, arg0: tuple) -> None:
        ...
    def deserialize(self, serialized: str) -> None:
        ...
    def graduatedLoss(self, error: typing.SupportsFloat | typing.SupportsIndex, mu: typing.SupportsFloat | typing.SupportsIndex) -> float:
        ...
    def graduatedWeight(self, error: typing.SupportsFloat | typing.SupportsIndex, mu: typing.SupportsFloat | typing.SupportsIndex) -> float:
        ...
    def loss(self, error: typing.SupportsFloat | typing.SupportsIndex) -> float:
        ...
    def serialize(self) -> str:
        ...
    def weight(self, error: typing.SupportsFloat | typing.SupportsIndex) -> float:
        ...
class Cauchy(Base):
    @staticmethod
    def Create(k: typing.SupportsFloat | typing.SupportsIndex, reweight: Base.ReweightScheme = ...) -> Cauchy:
        ...
    def __getstate__(self) -> tuple[str]:
        ...
    @typing.overload
    def __init__(self, k: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @typing.overload
    def __init__(self, k: typing.SupportsFloat | typing.SupportsIndex, reweight: Base.ReweightScheme) -> None:
        ...
    def __setstate__(self, arg0: tuple) -> None:
        ...
    def deserialize(self, serialized: str) -> None:
        ...
    def graduatedLoss(self, error: typing.SupportsFloat | typing.SupportsIndex, mu: typing.SupportsFloat | typing.SupportsIndex) -> float:
        ...
    def graduatedWeight(self, error: typing.SupportsFloat | typing.SupportsIndex, mu: typing.SupportsFloat | typing.SupportsIndex) -> float:
        ...
    def loss(self, error: typing.SupportsFloat | typing.SupportsIndex) -> float:
        ...
    def serialize(self) -> str:
        ...
    def weight(self, error: typing.SupportsFloat | typing.SupportsIndex) -> float:
        ...
class Tukey(Base):
    @staticmethod
    def Create(k: typing.SupportsFloat | typing.SupportsIndex, reweight: Base.ReweightScheme = ...) -> Tukey:
        ...
    def __getstate__(self) -> tuple[str]:
        ...
    @typing.overload
    def __init__(self, k: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @typing.overload
    def __init__(self, k: typing.SupportsFloat | typing.SupportsIndex, reweight: Base.ReweightScheme) -> None:
        ...
    def __setstate__(self, arg0: tuple) -> None:
        ...
    def deserialize(self, serialized: str) -> None:
        ...
    def graduatedLoss(self, error: typing.SupportsFloat | typing.SupportsIndex, mu: typing.SupportsFloat | typing.SupportsIndex) -> float:
        ...
    def graduatedWeight(self, error: typing.SupportsFloat | typing.SupportsIndex, mu: typing.SupportsFloat | typing.SupportsIndex) -> float:
        ...
    def loss(self, error: typing.SupportsFloat | typing.SupportsIndex) -> float:
        ...
    def serialize(self) -> str:
        ...
    def weight(self, error: typing.SupportsFloat | typing.SupportsIndex) -> float:
        ...
class Welsch(Base):
    @staticmethod
    def Create(k: typing.SupportsFloat | typing.SupportsIndex, reweight: Base.ReweightScheme = ...) -> Welsch:
        ...
    def __getstate__(self) -> tuple[str]:
        ...
    @typing.overload
    def __init__(self, k: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @typing.overload
    def __init__(self, k: typing.SupportsFloat | typing.SupportsIndex, reweight: Base.ReweightScheme) -> None:
        ...
    def __setstate__(self, arg0: tuple) -> None:
        ...
    def deserialize(self, serialized: str) -> None:
        ...
    def graduatedLoss(self, error: typing.SupportsFloat | typing.SupportsIndex, mu: typing.SupportsFloat | typing.SupportsIndex) -> float:
        ...
    def graduatedWeight(self, error: typing.SupportsFloat | typing.SupportsIndex, mu: typing.SupportsFloat | typing.SupportsIndex) -> float:
        ...
    def loss(self, error: typing.SupportsFloat | typing.SupportsIndex) -> float:
        ...
    def serialize(self) -> str:
        ...
    def weight(self, error: typing.SupportsFloat | typing.SupportsIndex) -> float:
        ...
class GemanMcClure(Base):
    class GradScheme:
        """
        Members:
        
          STANDARD
        
          SCALE_INVARIANT
        """
        SCALE_INVARIANT: typing.ClassVar[GemanMcClure.GradScheme]
        STANDARD: typing.ClassVar[GemanMcClure.GradScheme]
        __members__: typing.ClassVar[dict[str, GemanMcClure.GradScheme]]
        @typing.overload
        def __and__(self, other: GemanMcClure.GradScheme) -> int:
            ...
        @typing.overload
        def __and__(self, other: typing.SupportsInt | typing.SupportsIndex) -> int:
            ...
        @typing.overload
        def __eq__(self, other: GemanMcClure.GradScheme) -> bool:
            ...
        @typing.overload
        def __eq__(self, other: typing.SupportsInt | typing.SupportsIndex) -> bool:
            ...
        @typing.overload
        def __eq__(self, other: typing.Any) -> bool:
            ...
        @typing.overload
        def __ge__(self, other: GemanMcClure.GradScheme) -> bool:
            ...
        @typing.overload
        def __ge__(self, other: typing.SupportsInt | typing.SupportsIndex) -> bool:
            ...
        def __getstate__(self) -> int:
            ...
        @typing.overload
        def __gt__(self, other: GemanMcClure.GradScheme) -> bool:
            ...
        @typing.overload
        def __gt__(self, other: typing.SupportsInt | typing.SupportsIndex) -> bool:
            ...
        def __hash__(self) -> int:
            ...
        def __index__(self) -> int:
            ...
        def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None:
            ...
        def __int__(self) -> int:
            ...
        def __invert__(self) -> typing.Any:
            ...
        @typing.overload
        def __le__(self, other: GemanMcClure.GradScheme) -> bool:
            ...
        @typing.overload
        def __le__(self, other: typing.SupportsInt | typing.SupportsIndex) -> bool:
            ...
        @typing.overload
        def __lt__(self, other: GemanMcClure.GradScheme) -> bool:
            ...
        @typing.overload
        def __lt__(self, other: typing.SupportsInt | typing.SupportsIndex) -> bool:
            ...
        @typing.overload
        def __ne__(self, other: GemanMcClure.GradScheme) -> bool:
            ...
        @typing.overload
        def __ne__(self, other: typing.SupportsInt | typing.SupportsIndex) -> bool:
            ...
        @typing.overload
        def __ne__(self, other: typing.Any) -> bool:
            ...
        @typing.overload
        def __or__(self, other: GemanMcClure.GradScheme) -> int:
            ...
        @typing.overload
        def __or__(self, other: typing.SupportsInt | typing.SupportsIndex) -> int:
            ...
        @typing.overload
        def __rand__(self, other: GemanMcClure.GradScheme) -> int:
            ...
        @typing.overload
        def __rand__(self, other: typing.SupportsInt | typing.SupportsIndex) -> int:
            ...
        def __repr__(self) -> str:
            ...
        @typing.overload
        def __ror__(self, other: GemanMcClure.GradScheme) -> int:
            ...
        @typing.overload
        def __ror__(self, other: typing.SupportsInt | typing.SupportsIndex) -> int:
            ...
        @typing.overload
        def __rxor__(self, other: GemanMcClure.GradScheme) -> int:
            ...
        @typing.overload
        def __rxor__(self, other: typing.SupportsInt | typing.SupportsIndex) -> int:
            ...
        def __setstate__(self, state: typing.SupportsInt | typing.SupportsIndex) -> None:
            ...
        def __str__(self) -> str:
            ...
        @typing.overload
        def __xor__(self, other: GemanMcClure.GradScheme) -> int:
            ...
        @typing.overload
        def __xor__(self, other: typing.SupportsInt | typing.SupportsIndex) -> int:
            ...
        @property
        def name(self) -> str:
            ...
        @property
        def value(self) -> int:
            ...
    @staticmethod
    @typing.overload
    def Create(c: typing.SupportsFloat | typing.SupportsIndex, reweight: Base.ReweightScheme = ...) -> GemanMcClure:
        ...
    @staticmethod
    @typing.overload
    def Create(c: typing.SupportsFloat | typing.SupportsIndex, graduation: GemanMcClure.GradScheme, reweight: Base.ReweightScheme = ...) -> GemanMcClure:
        ...
    def __getstate__(self) -> tuple[str]:
        ...
    @typing.overload
    def __init__(self, c: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @typing.overload
    def __init__(self, c: typing.SupportsFloat | typing.SupportsIndex, reweight: Base.ReweightScheme) -> None:
        ...
    @typing.overload
    def __init__(self, c: typing.SupportsFloat | typing.SupportsIndex, graduation: GemanMcClure.GradScheme) -> None:
        ...
    @typing.overload
    def __init__(self, c: typing.SupportsFloat | typing.SupportsIndex, graduation: GemanMcClure.GradScheme, reweight: Base.ReweightScheme) -> None:
        ...
    def __setstate__(self, arg0: tuple) -> None:
        ...
    def deserialize(self, serialized: str) -> None:
        ...
    def graduatedLoss(self, error: typing.SupportsFloat | typing.SupportsIndex, mu: typing.SupportsFloat | typing.SupportsIndex) -> float:
        ...
    def graduatedWeight(self, error: typing.SupportsFloat | typing.SupportsIndex, mu: typing.SupportsFloat | typing.SupportsIndex) -> float:
        ...
    def loss(self, error: typing.SupportsFloat | typing.SupportsIndex) -> float:
        ...
    def serialize(self) -> str:
        ...
    def weight(self, error: typing.SupportsFloat | typing.SupportsIndex) -> float:
        ...
class TruncatedLeastSquares(Base):
    class GradScheme:
        """
        Members:
        
          STANDARD
        
          GNC_LINEAR
        
          GNC_SUPERLINEAR
        """
        GNC_LINEAR: typing.ClassVar[TruncatedLeastSquares.GradScheme]
        GNC_SUPERLINEAR: typing.ClassVar[TruncatedLeastSquares.GradScheme]
        STANDARD: typing.ClassVar[TruncatedLeastSquares.GradScheme]
        __members__: typing.ClassVar[dict[str, TruncatedLeastSquares.GradScheme]]
        @typing.overload
        def __and__(self, other: TruncatedLeastSquares.GradScheme) -> int:
            ...
        @typing.overload
        def __and__(self, other: typing.SupportsInt | typing.SupportsIndex) -> int:
            ...
        @typing.overload
        def __eq__(self, other: TruncatedLeastSquares.GradScheme) -> bool:
            ...
        @typing.overload
        def __eq__(self, other: typing.SupportsInt | typing.SupportsIndex) -> bool:
            ...
        @typing.overload
        def __eq__(self, other: typing.Any) -> bool:
            ...
        @typing.overload
        def __ge__(self, other: TruncatedLeastSquares.GradScheme) -> bool:
            ...
        @typing.overload
        def __ge__(self, other: typing.SupportsInt | typing.SupportsIndex) -> bool:
            ...
        def __getstate__(self) -> int:
            ...
        @typing.overload
        def __gt__(self, other: TruncatedLeastSquares.GradScheme) -> bool:
            ...
        @typing.overload
        def __gt__(self, other: typing.SupportsInt | typing.SupportsIndex) -> bool:
            ...
        def __hash__(self) -> int:
            ...
        def __index__(self) -> int:
            ...
        def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None:
            ...
        def __int__(self) -> int:
            ...
        def __invert__(self) -> typing.Any:
            ...
        @typing.overload
        def __le__(self, other: TruncatedLeastSquares.GradScheme) -> bool:
            ...
        @typing.overload
        def __le__(self, other: typing.SupportsInt | typing.SupportsIndex) -> bool:
            ...
        @typing.overload
        def __lt__(self, other: TruncatedLeastSquares.GradScheme) -> bool:
            ...
        @typing.overload
        def __lt__(self, other: typing.SupportsInt | typing.SupportsIndex) -> bool:
            ...
        @typing.overload
        def __ne__(self, other: TruncatedLeastSquares.GradScheme) -> bool:
            ...
        @typing.overload
        def __ne__(self, other: typing.SupportsInt | typing.SupportsIndex) -> bool:
            ...
        @typing.overload
        def __ne__(self, other: typing.Any) -> bool:
            ...
        @typing.overload
        def __or__(self, other: TruncatedLeastSquares.GradScheme) -> int:
            ...
        @typing.overload
        def __or__(self, other: typing.SupportsInt | typing.SupportsIndex) -> int:
            ...
        @typing.overload
        def __rand__(self, other: TruncatedLeastSquares.GradScheme) -> int:
            ...
        @typing.overload
        def __rand__(self, other: typing.SupportsInt | typing.SupportsIndex) -> int:
            ...
        def __repr__(self) -> str:
            ...
        @typing.overload
        def __ror__(self, other: TruncatedLeastSquares.GradScheme) -> int:
            ...
        @typing.overload
        def __ror__(self, other: typing.SupportsInt | typing.SupportsIndex) -> int:
            ...
        @typing.overload
        def __rxor__(self, other: TruncatedLeastSquares.GradScheme) -> int:
            ...
        @typing.overload
        def __rxor__(self, other: typing.SupportsInt | typing.SupportsIndex) -> int:
            ...
        def __setstate__(self, state: typing.SupportsInt | typing.SupportsIndex) -> None:
            ...
        def __str__(self) -> str:
            ...
        @typing.overload
        def __xor__(self, other: TruncatedLeastSquares.GradScheme) -> int:
            ...
        @typing.overload
        def __xor__(self, other: typing.SupportsInt | typing.SupportsIndex) -> int:
            ...
        @property
        def name(self) -> str:
            ...
        @property
        def value(self) -> int:
            ...
    @staticmethod
    @typing.overload
    def Create(c: typing.SupportsFloat | typing.SupportsIndex, reweight: Base.ReweightScheme = ...) -> TruncatedLeastSquares:
        ...
    @staticmethod
    @typing.overload
    def Create(c: typing.SupportsFloat | typing.SupportsIndex, graduation: TruncatedLeastSquares.GradScheme, reweight: Base.ReweightScheme = ...) -> TruncatedLeastSquares:
        ...
    def __getstate__(self) -> tuple[str]:
        ...
    @typing.overload
    def __init__(self, c: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @typing.overload
    def __init__(self, c: typing.SupportsFloat | typing.SupportsIndex, reweight: Base.ReweightScheme) -> None:
        ...
    @typing.overload
    def __init__(self, c: typing.SupportsFloat | typing.SupportsIndex, graduation: TruncatedLeastSquares.GradScheme) -> None:
        ...
    @typing.overload
    def __init__(self, c: typing.SupportsFloat | typing.SupportsIndex, graduation: TruncatedLeastSquares.GradScheme, reweight: Base.ReweightScheme) -> None:
        ...
    def __setstate__(self, arg0: tuple) -> None:
        ...
    def deserialize(self, serialized: str) -> None:
        ...
    def graduatedLoss(self, error: typing.SupportsFloat | typing.SupportsIndex, mu: typing.SupportsFloat | typing.SupportsIndex) -> float:
        ...
    def graduatedWeight(self, error: typing.SupportsFloat | typing.SupportsIndex, mu: typing.SupportsFloat | typing.SupportsIndex) -> float:
        ...
    def loss(self, error: typing.SupportsFloat | typing.SupportsIndex) -> float:
        ...
    def serialize(self) -> str:
        ...
    def weight(self, error: typing.SupportsFloat | typing.SupportsIndex) -> float:
        ...
class DCS(Base):
    @staticmethod
    def Create(c: typing.SupportsFloat | typing.SupportsIndex, reweight: Base.ReweightScheme = ...) -> DCS:
        ...
    def __getstate__(self) -> tuple[str]:
        ...
    @typing.overload
    def __init__(self, c: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @typing.overload
    def __init__(self, c: typing.SupportsFloat | typing.SupportsIndex, reweight: Base.ReweightScheme) -> None:
        ...
    def __setstate__(self, arg0: tuple) -> None:
        ...
    def deserialize(self, serialized: str) -> None:
        ...
    def graduatedLoss(self, error: typing.SupportsFloat | typing.SupportsIndex, mu: typing.SupportsFloat | typing.SupportsIndex) -> float:
        ...
    def graduatedWeight(self, error: typing.SupportsFloat | typing.SupportsIndex, mu: typing.SupportsFloat | typing.SupportsIndex) -> float:
        ...
    def loss(self, error: typing.SupportsFloat | typing.SupportsIndex) -> float:
        ...
    def serialize(self) -> str:
        ...
    def weight(self, error: typing.SupportsFloat | typing.SupportsIndex) -> float:
        ...
class L2WithDeadZone(Base):
    @staticmethod
    def Create(k: typing.SupportsFloat | typing.SupportsIndex, reweight: Base.ReweightScheme = ...) -> L2WithDeadZone:
        ...
    def __getstate__(self) -> tuple[str]:
        ...
    @typing.overload
    def __init__(self, k: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @typing.overload
    def __init__(self, k: typing.SupportsFloat | typing.SupportsIndex, reweight: Base.ReweightScheme) -> None:
        ...
    def __setstate__(self, arg0: tuple) -> None:
        ...
    def deserialize(self, serialized: str) -> None:
        ...
    def graduatedLoss(self, error: typing.SupportsFloat | typing.SupportsIndex, mu: typing.SupportsFloat | typing.SupportsIndex) -> float:
        ...
    def graduatedWeight(self, error: typing.SupportsFloat | typing.SupportsIndex, mu: typing.SupportsFloat | typing.SupportsIndex) -> float:
        ...
    def loss(self, error: typing.SupportsFloat | typing.SupportsIndex) -> float:
        ...
    def serialize(self) -> str:
        ...
    def weight(self, error: typing.SupportsFloat | typing.SupportsIndex) -> float:
        ...
class AsymmetricTukey(Base):
    @staticmethod
    def Create(k: typing.SupportsFloat | typing.SupportsIndex, reweight: Base.ReweightScheme = ...) -> AsymmetricTukey:
        ...
    def __getstate__(self) -> tuple[str]:
        ...
    @typing.overload
    def __init__(self, k: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @typing.overload
    def __init__(self, k: typing.SupportsFloat | typing.SupportsIndex, reweight: Base.ReweightScheme) -> None:
        ...
    def __setstate__(self, arg0: tuple) -> None:
        ...
    def deserialize(self, serialized: str) -> None:
        ...
    def graduatedLoss(self, error: typing.SupportsFloat | typing.SupportsIndex, mu: typing.SupportsFloat | typing.SupportsIndex) -> float:
        ...
    def graduatedWeight(self, error: typing.SupportsFloat | typing.SupportsIndex, mu: typing.SupportsFloat | typing.SupportsIndex) -> float:
        ...
    def loss(self, error: typing.SupportsFloat | typing.SupportsIndex) -> float:
        ...
    def serialize(self) -> str:
        ...
    def weight(self, error: typing.SupportsFloat | typing.SupportsIndex) -> float:
        ...
class AsymmetricCauchy(Base):
    @staticmethod
    def Create(k: typing.SupportsFloat | typing.SupportsIndex, reweight: Base.ReweightScheme = ...) -> AsymmetricCauchy:
        ...
    def __getstate__(self) -> tuple[str]:
        ...
    @typing.overload
    def __init__(self, k: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @typing.overload
    def __init__(self, k: typing.SupportsFloat | typing.SupportsIndex, reweight: Base.ReweightScheme) -> None:
        ...
    def __setstate__(self, arg0: tuple) -> None:
        ...
    def deserialize(self, serialized: str) -> None:
        ...
    def graduatedLoss(self, error: typing.SupportsFloat | typing.SupportsIndex, mu: typing.SupportsFloat | typing.SupportsIndex) -> float:
        ...
    def graduatedWeight(self, error: typing.SupportsFloat | typing.SupportsIndex, mu: typing.SupportsFloat | typing.SupportsIndex) -> float:
        ...
    def loss(self, error: typing.SupportsFloat | typing.SupportsIndex) -> float:
        ...
    def serialize(self) -> str:
        ...
    def weight(self, error: typing.SupportsFloat | typing.SupportsIndex) -> float:
        ...
class Custom(Base):
    @staticmethod
    def Create(weight: collections.abc.Callable[[float], typing.SupportsFloat | typing.SupportsIndex], loss: collections.abc.Callable[[float], typing.SupportsFloat | typing.SupportsIndex], gradWeight: collections.abc.Callable[[float, float], typing.SupportsFloat | typing.SupportsIndex] | None = None, gradLoss: collections.abc.Callable[[float, float], typing.SupportsFloat | typing.SupportsIndex] | None = None, reweight: Base.ReweightScheme = ..., name: str = 'Custom') -> Custom:
        ...
    def __getstate__(self) -> tuple[str]:
        ...
    @typing.overload
    def __init__(self, weight: collections.abc.Callable[[float], typing.SupportsFloat | typing.SupportsIndex], loss: collections.abc.Callable[[float], typing.SupportsFloat | typing.SupportsIndex]) -> None:
        ...
    @typing.overload
    def __init__(self, weight: collections.abc.Callable[[float], typing.SupportsFloat | typing.SupportsIndex], loss: collections.abc.Callable[[float], typing.SupportsFloat | typing.SupportsIndex], reweight: Base.ReweightScheme, name: str) -> None:
        ...
    @typing.overload
    def __init__(self, weight: collections.abc.Callable[[float], typing.SupportsFloat | typing.SupportsIndex], loss: collections.abc.Callable[[float], typing.SupportsFloat | typing.SupportsIndex], gradWeight: collections.abc.Callable[[float, float], typing.SupportsFloat | typing.SupportsIndex] | None, gradLoss: collections.abc.Callable[[float, float], typing.SupportsFloat | typing.SupportsIndex] | None, reweight: Base.ReweightScheme, name: str) -> None:
        ...
    def __setstate__(self, arg0: tuple) -> None:
        ...
    def deserialize(self, serialized: str) -> None:
        ...
    def graduatedLoss(self, error: typing.SupportsFloat | typing.SupportsIndex, mu: typing.SupportsFloat | typing.SupportsIndex) -> float:
        ...
    def graduatedWeight(self, error: typing.SupportsFloat | typing.SupportsIndex, mu: typing.SupportsFloat | typing.SupportsIndex) -> float:
        ...
    def loss(self, error: typing.SupportsFloat | typing.SupportsIndex) -> float:
        ...
    def serialize(self) -> str:
        ...
    def weight(self, error: typing.SupportsFloat | typing.SupportsIndex) -> float:
        ...
